import test from 'node:test';
import assert from 'node:assert/strict';
import { fresh, openAccount, creditDeposit, balance, place, cancel, applyCommand, reserveWithdrawal, invariant, START_USD } from '../work/engine.mjs';
import { wallet, walletId, accountId, prepareWithdrawal, testnetAddress } from '../work/bitcoin.mjs';
import { Transaction, Psbt, networks } from 'bitcoinjs-lib';
const seed = '11'.repeat(32), now = new Date().toISOString();
const ids = ['Alice','Bob'].map(p => accountId('unit-test-owner',p));
function setup(funded=true) { const s=fresh(); ['Alice','Bob'].forEach((person,i)=> { const w=wallet(seed,ids[i]); openAccount(s,{id:ids[i],person,sats:0,usd:0,address:w.address,script:w.script},walletId(seed)); }); if(funded) creditDeposit(s,ids[0],proof(),now); return s; }
function proof(conf=6) { return {txid:'ab'.repeat(32),outputs:[{script:wallet(seed,ids[0]).script,value:200000}],confirmations:conf,inBestChain:true}; }
function command(s, fn, id=crypto.randomUUID(), payload='test') { return applyCommand(s,id,payload,fn); }
test('new accounts have simulated dollars but no Bitcoin',()=>{const s=setup(false);assert.equal(s.accounts[ids[0]].usd,START_USD);assert.equal(balance(s,ids[0]).sats,0);invariant(s)});
test('unfunded sell fails without mutating the original state',()=>{const s=setup(false),before=JSON.stringify(s);assert.throws(()=>command(s,x=>place(x,ids[0],'sell',60000,1000,now)),/Deposit/);assert.equal(JSON.stringify(s),before)});
test('deposit needs six confirmations and credits once',()=>{let s=setup(false);creditDeposit(s,ids[0],proof(5),now);assert.equal(s.accounts[ids[0]].sats,0);creditDeposit(s,ids[0],proof(6),now);creditDeposit(s,ids[0],proof(9),now);assert.equal(s.accounts[ids[0]].sats,200000);assert.equal(s.coins.length,1);invariant(s)});
test('wrong recipient and direct mining reward deposits are rejected',()=>{const s=setup(false);assert.throws(()=>creditDeposit(s,ids[1],proof(),now),/does not pay/);assert.throws(()=>creditDeposit(s,ids[0],{...proof(),coinbase:true},now),/mining/)});
test('confirmation loss freezes trading',()=>{const s=setup();creditDeposit(s,ids[0],proof(1),now);assert.ok(s.frozen);assert.throws(()=>place(s,ids[0],'sell',60000,1000,now),/confirmations/)});
test('partial fills settle Bitcoin and USD atomically at maker price',()=>{let s=setup();s=command(s,x=>place(x,ids[0],'sell',60000,10000,now));s=command(s,x=>place(x,ids[1],'buy',61000,4000,now));assert.equal(s.trades[0].price,60000);assert.equal(s.accounts[ids[1]].sats,4000);assert.equal(s.accounts[ids[1]].usd,START_USD-2400000);assert.equal(balance(s,ids[0]).reservedSats,6000);invariant(s)});
test('price then FIFO decides fill order',()=>{let s=setup();for(const p of [61000,60000,60000])s=command(s,x=>place(x,ids[0],'sell',p,1000,now));s=command(s,x=>place(x,ids[1],'buy',61000,2000,now));assert.deepEqual(s.trades.map(t=>t.price),[60000,60000]);assert.equal(s.orders[0].remaining,1000);assert.equal(s.orders[1].remaining,0)});
test('same subaccount cannot match itself',()=>{let s=setup();s=command(s,x=>place(x,ids[0],'sell',60000,1000,now));s=command(s,x=>place(x,ids[0],'buy',60000,1000,now));assert.equal(s.trades.length,0)});
test('cancellation releases reserves and enforces ownership',()=>{let s=setup();s=command(s,x=>place(x,ids[0],'sell',60000,10000,now));const id=s.orders[0].id;assert.throws(()=>command(s,x=>cancel(x,ids[1],id,now)),/No open/);s=command(s,x=>cancel(x,ids[0],id,now));assert.equal(balance(s,ids[0]).reservedSats,0)});
test('buy reservations prevent overspending',()=>{let s=setup();for(let i=0;i<10;i++)s=command(s,x=>place(x,ids[1],'buy',1000000,1000000,now));assert.equal(balance(s,ids[1]).availableUSD,0);assert.throws(()=>command(s,x=>place(x,ids[1],'buy',1000000,1000,now)),/Not enough/)});
test('request replay is idempotent and changed payload fails',()=>{const id=crypto.randomUUID();let s=command(setup(),x=>place(x,ids[0],'sell',60000,1000,now),id,'a');const same=command(s,()=>assert.fail(),id,'a');assert.equal(same,s);assert.throws(()=>command(s,()=>{},id,'b'),/reused/)});
test('invalid sizes and noninteger prices fail',()=>{for(const [p,q] of [[1.1,1000],[60000,1500],[0,1000],[60000,-1],[Infinity,1000]]) assert.throws(()=>command(setup(),x=>place(x,ids[0],'sell',p,q,now)))});
test('wallets are deterministic, isolated, and Testnet only',()=>{assert.equal(wallet(seed,ids[0]).address,wallet(seed,ids[0]).address);assert.notEqual(wallet(seed,ids[0]).address,wallet(seed,ids[1]).address);assert.ok(wallet(seed,ids[0]).address.startsWith('tb1'));assert.throws(()=>testnetAddress('1BoatSLRHtKNngkdXEeobR76b53LETtpyT'),/Mainnet/);assert.throws(()=>wallet('',ids[0]),/configured/)});
test('seed changes fail closed',()=>{const s=setup();assert.throws(()=>openAccount(s,{id:'other'},walletId('22'.repeat(32))),/changed/)});
test('withdrawal signs valid inputs, preserves conservation, and debits once',()=>{let s=setup();const to=wallet(seed,'external');const p=prepareWithdrawal(seed,s.coins,ids[0],crypto.randomUUID(),to.address,10000,1,now);const tx=Transaction.fromHex(p.withdrawal.raw);assert.equal(tx.getId(),p.withdrawal.txid);assert.equal(tx.outs[0].value,10000n);assert.equal(tx.ins[0].witness.length,2);s=command(s,x=>reserveWithdrawal(x,p.withdrawal,p.changeScript,now));assert.equal(s.accounts[ids[0]].sats,200000-10000-p.withdrawal.fee);assert.equal(s.coins.filter(c=>!c.spentBy).length,1);invariant(s);assert.throws(()=>command(s,x=>reserveWithdrawal(x,p.withdrawal,p.changeScript,now)),/prepared/)});
test('withdrawal cannot spend reserved sell balance',()=>{let s=setup();s=command(s,x=>place(x,ids[0],'sell',60000,200000,now));const p=prepareWithdrawal(seed,s.coins,ids[0],crypto.randomUUID(),wallet(seed,'external').address,1000,1,now);assert.throws(()=>command(s,x=>reserveWithdrawal(x,p.withdrawal,p.changeScript,now)),/Insufficient/)});
test('competing withdrawals cannot reuse an input',()=>{let s=setup();s=command(s,x=>place(x,ids[0],'sell',60000,100000,now));s=command(s,x=>place(x,ids[1],'buy',60000,100000,now));const to=wallet(seed,'external').address,p1=prepareWithdrawal(seed,s.coins,ids[0],crypto.randomUUID(),to,1000,1,now),p2=prepareWithdrawal(seed,s.coins,ids[1],crypto.randomUUID(),to,1000,1,now);s=command(s,x=>reserveWithdrawal(x,p1.withdrawal,p1.changeScript,now));assert.throws(()=>command(s,x=>reserveWithdrawal(x,p2.withdrawal,p2.changeScript,now)),/Wallet changed/)});
test('random matched trades and cancellations conserve both assets',()=>{let s=setup();for(let i=0;i<100;i++){const seller=i%2?ids[1]:ids[0],buyer=i%2?ids[0]:ids[1];s=command(s,x=>place(x,seller,'sell',50000+i,1000,now));s=command(s,x=>place(x,buyer,'buy',50000+i,1000,now));invariant(s)}assert.equal(s.accounts[ids[0]].sats,200000)});
