import { address, networks, payments, Psbt, Transaction } from 'bitcoinjs-lib';
import * as ecc from '@bitcoinerlab/secp256k1';
import { ECPairFactory } from 'ecpair';
import { createHash, createHmac } from 'node:crypto';
import { type Coin, type Proof, type State, type Withdrawal, integer } from './engine';
const ECPair = ECPairFactory(ecc);
export const MEMPOOL = 'https://mempool.space/testnet4/api';
export function wallet(seed: string, id: string) { if (!/^[a-f0-9]{64}$/i.test(seed || '')) throw Error('The Testnet wallet is not configured.'); const key = ECPair.fromPrivateKey(createHmac('sha256', Buffer.from(seed, 'hex')).update('lazer:testnet4:v2:' + id).digest(), { network: networks.testnet }); const p = payments.p2wpkh({ pubkey: key.publicKey, network: networks.testnet }); return { key, address: p.address!, script: Buffer.from(p.output!).toString('hex') }; }
export const walletId = (seed: string) => createHash('sha256').update(wallet(seed, 'treasury').address).digest('hex');
export const accountId = (owner: string, person: string) => createHash('sha256').update('lazer:v2:' + owner + ':' + person).digest('hex');
export function testnetAddress(value: unknown) { if (typeof value !== 'string' || value.length > 100) throw Error('Enter a Testnet Bitcoin address.'); try { const script = address.toOutputScript(value.trim(), networks.testnet); return { address: address.fromOutputScript(script, networks.testnet), script: Buffer.from(script).toString('hex') }; } catch { throw Error('Invalid Testnet Bitcoin address or checksum. Mainnet addresses are not accepted.'); } }
export async function api(path: string): Promise<any> { const res = await fetch(MEMPOOL + path, { headers: { Accept: 'application/json' }, signal: AbortSignal.timeout(12000), cache: 'no-store' }); if (res.status === 404) return null; if (!res.ok) throw Error('Testnet data provider is unavailable. No balance change was assumed.'); return res.json(); }
export async function transactionProof(txid: unknown): Promise<Proof | null> { if (typeof txid !== 'string' || !/^[a-f0-9]{64}$/i.test(txid)) throw Error('Enter a 64 character transaction ID.'); const normalized = txid.toLowerCase(), tx = await api('/tx/' + normalized); if (!tx) return null; if (tx.txid !== normalized || !Array.isArray(tx.vout) || tx.vout.length > 10000) throw Error('Unexpected transaction response.'); let confirmations = 0, inBestChain = false; if (tx.status?.confirmed) { const [tip, block] = await Promise.all([api('/blocks/tip/height'), api('/block/' + tx.status.block_hash + '/status')]); if (!Number.isSafeInteger(tip) || !Number.isSafeInteger(tx.status.block_height) || typeof block?.in_best_chain !== 'boolean') throw Error('Unable to verify block confirmations.'); inBestChain = block.in_best_chain; confirmations = inBestChain ? Math.max(0, tip - tx.status.block_height + 1) : 0; } for (const o of tx.vout) { integer(o.value, 0, 2_100_000_000_000_000, 'Output'); if (!/^[a-f0-9]*$/i.test(o.scriptpubkey)) throw Error('Invalid output script.'); } return { txid: normalized, outputs: tx.vout.map((o: any) => ({ script: o.scriptpubkey, value: o.value })), confirmations, inBestChain, blockHeight: tx.status?.block_height, coinbase: tx.vin?.some((v: any) => v.is_coinbase) }; }
export async function eligibleCoins(s: State) {
 const coins = s.coins.filter(c => !c.spentBy); if (coins.length > 100) throw Error('Wallet input capacity reached. Contact the operator to consolidate test coins.'); const txids = [...new Set(coins.map(c => c.txid))], proofs = new Map<string, Proof | null>();
 for (let i = 0; i < txids.length; i += 5) { const batch = await Promise.all(txids.slice(i, i + 5).map(async id => [id, await transactionProof(id)] as const)); for (const [id, proof] of batch) proofs.set(id, proof); }
 const eligible: Coin[] = []; for (const coin of coins) { const p = proofs.get(coin.txid), change = s.withdrawals.some(w => w.txid === coin.txid); if (!p || !p.inBestChain || p.confirmations < 6) { if (!change) throw Error('A backing deposit lost confirmations. Trading is paused until it is confirmed again.'); continue; } const out = p.outputs[coin.vout]; if (!out || out.value !== coin.sats || out.script !== coin.script) throw Error('Bitcoin backing mismatch. Contact the operator.'); const spend = await api(`/tx/${coin.txid}/outspend/${coin.vout}`); if (!spend || typeof spend.spent !== 'boolean') throw Error('Cannot verify wallet inputs.'); if (spend.spent) throw Error('A wallet input was spent outside Lazer. Trading is paused for review.'); eligible.push(coin); } return eligible;
}
export function prepareWithdrawal(seed: string, coins: Coin[], id: string, requestId: string, destination: string, sats: number, rate: number, now: string): { withdrawal: Withdrawal; changeScript: string } {
 integer(sats, 1000, 1_000_000, 'Withdrawal satoshis'); integer(rate, 1, 100, 'Fee rate'); const target = testnetAddress(destination), change = wallet(seed, 'treasury'); const selected: Coin[] = []; let total = 0, fee = 0;
 for (const c of [...coins].sort((a, b) => b.sats - a.sats)) { selected.push(c); total += c.sats; fee = Math.ceil((12 + 69 * selected.length + 8 + 1 + target.script.length / 2 + 31) * rate); if (total >= sats + fee) break; }
 if (total < sats + fee || !selected.length) throw Error('No confirmed wallet inputs can cover this withdrawal yet. Change from recent withdrawals needs six confirmations.'); let changeSats = total - sats - fee; if (changeSats < 546) { fee += changeSats; changeSats = 0; } if (fee > 100_000) throw Error('Estimated network fee exceeds the Testnet limit.');
 const psbt = new Psbt({ network: networks.testnet }); for (const c of selected) { const own = wallet(seed, c.account); if (own.script !== c.script) throw Error('Wallet secret does not match deposit backing.'); psbt.addInput({ hash: c.txid, index: c.vout, sequence: 0xfffffffe, witnessUtxo: { script: Buffer.from(c.script, 'hex'), value: BigInt(c.sats) } }); } psbt.addOutput({ script: Buffer.from(target.script, 'hex'), value: BigInt(sats) }); if (changeSats) psbt.addOutput({ address: change.address, value: BigInt(changeSats) }); selected.forEach((c, i) => psbt.signInput(i, wallet(seed, c.account).key)); psbt.finalizeAllInputs(); const tx = psbt.extractTransaction(); return { withdrawal: { id: requestId, account: id, address: target.address, sats, fee, txid: tx.getId(), raw: tx.toHex(), inputs: selected.map(c => c.id), change: changeSats, createdAt: now, status: 'prepared', confirmations: 0 }, changeScript: change.script };
}
export async function broadcast(w: Withdrawal) { if (Transaction.fromHex(w.raw).getId() !== w.txid) throw Error('Stored withdrawal transaction is invalid.'); const existing = await api('/tx/' + w.txid); if (existing) return; const res = await fetch(MEMPOOL + '/tx', { method: 'POST', headers: { 'Content-Type': 'text/plain' }, body: w.raw, signal: AbortSignal.timeout(15000) }); if (!res.ok) throw Error('Broadcast could not be confirmed. Retry this same withdrawal; its funds stay reserved.'); if ((await res.text()).trim() !== w.txid) throw Error('Broadcast response was unexpected. Check the saved transaction ID.'); }
