import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { applyCommand, fresh, type State, type Person, balance } from './engine';
import { accountId } from './bitcoin';
const KEY = 'lazer-testnet4-v2';
export async function identity(optional = false) { const user = await getChatGPTUser(); if (!user && !optional) throw Error('Sign in to open your trading accounts.'); return user?.userId || null; }
export function seed() { return (env as unknown as { TESTNET_WALLET_SEED?: string }).TESTNET_WALLET_SEED || ''; }
function db() { const binding = (env as unknown as { DB?: D1Database }).DB; if (!binding) throw Error('Trading storage is unavailable.'); return binding; }
export async function readState() { const row = await db().prepare('SELECT revision,state FROM exchange_sessions WHERE id=?').bind(KEY).first<{ revision: number; state: string }>(); return row ? { revision: row.revision, state: JSON.parse(row.state) as State } : { revision: 0, state: fresh() }; }
export async function changeState(id: string, payload: string, mutate: (s: State) => void) { await db().prepare('INSERT OR IGNORE INTO exchange_sessions (id,revision,state) VALUES (?,0,?)').bind(KEY, JSON.stringify(fresh())).run(); for (let i = 0; i < 8; i++) { const old = await readState(), next = applyCommand(old.state, id, payload, mutate); if (old.state === next) return old; const r = await db().prepare('UPDATE exchange_sessions SET state=?,revision=revision+1 WHERE id=? AND revision=?').bind(JSON.stringify(next), KEY, old.revision).run(); if (r.meta.changes === 1) return { state: next, revision: old.revision + 1 }; } throw Error('The order book changed. Retry your action.'); }
export function view(s: State, owner: string | null, revision: number) { const ids = owner ? (['Alice','Bob'] as Person[]).map(p => accountId(owner, p)) : [], mine = (id: string) => ids.includes(id), ownedOrders = s.orders.filter(o => mine(o.account)), recentOrders = new Set(ownedOrders.slice(-100).map(o => o.id)); return { revision, network: 'testnet4', authenticated: !!owner, frozen: s.frozen, accounts: ids.filter(id => s.accounts[id]).map(id => ({ ...s.accounts[id], ...balance(s, id) })), orders: ownedOrders.filter(o => o.remaining > 0 && !o.cancelled || recentOrders.has(o.id)), book: s.orders.filter(o => o.remaining && !o.cancelled).map(o => ({ id: o.id, person: o.person, side: o.side, price: o.price, remaining: o.remaining, seq: o.seq, mine: mine(o.account) })), trades: s.trades.slice(-100).map(t => ({ ...t, buyer: s.accounts[t.buyer]?.person, seller: s.accounts[t.seller]?.person, mine: mine(t.buyer) || mine(t.seller) })), deposits: s.deposits.filter(d => mine(d.account)), withdrawals: s.withdrawals.filter(w => mine(w.account)).map(({ raw, inputs, ...w }) => w), events: s.events.filter(e => e.accounts.some(mine)).slice(-100).map(({ accounts, ...e }) => e) }; }
export type View = ReturnType<typeof view>;
export async function rateLimit(owner: string) { const bucket = Math.floor(Date.now() / 60000); const row = await db().prepare('INSERT INTO request_limits (id,window,count) VALUES (?, ?, 1) ON CONFLICT(id) DO UPDATE SET window=excluded.window,count=CASE WHEN request_limits.window=excluded.window THEN request_limits.count+1 ELSE 1 END RETURNING count').bind(accountId(owner, 'rate'), bucket).first<{count:number}>(); if (!row || row.count > 30) throw Error('Too many requests. Wait one minute and try again.'); }
